### PR TITLE
Add nix flake (derivation + direnv)

### PR DESCRIPTION
**Pull request by Sigmanificient**
As `PKGBUILD`, the `flake.nix` & `flake.lock`  file provide a way to build a [nix derivation](https://nixos.org/manual/nix/stable/language/derivations.html) (package) for [NixOS](https://nixos.org/).
I've made a [Pull Request](https://github.com/NixOS/nixpkgs/pull/247909) for `ragnarwm` within the official [nixpkgs repository](https://github.com/NixOS/nixpkgs) along side this pull request.

Build ragner using nix
```sh
nix build .
```

> Note: [Flakes](https://nixos.wiki/wiki/Flakes) are still an "experimental feature" of nix despite its wide use.

Moreover, this `flake.nix` provides a [shell](https://nixos.org/manual/nix/stable/command-ref/nix-shell.html) with the dependencies required to compile this project.
This means that in any Linux distributions, windows WSL or even OSX, and other system supporting the [nix package manager](https://nixos.org/download) you use use it to pull the dependencies and enters in a development shell with everything setup for you.

Entering the shell
```sh
nix develop
# do casual stuff
make
```

This can integrate with [direnv](https://direnv.net/) to automatically loads thoses dependencies went you enter the directory, once enabled.
direnv can integrate within multiples shells (bash, zsh, fish, tcsh, ...)

How to setup automatic direnv in project:
```sh
echo "use flake" | tee -a .envrc
direnv allow
```

### CODE REVIEW

**Comment by cococry** [comment]
That's amazing. Thank you

**Comment by Sigmanificient** [comment]
@cococry Update on nixpkgs, got `RagnarWm` to works natively on NixOS, within an automated test!
image

**Comment by cococry** [comment]
Thanks a lot for the effort, really appreciating it!
Yohann Boniface ***@***.***> schrieb am Fr. 18. Aug. 2023 um
19:34:

**Comment by Sigmanificient** [comment]
@cococry 
Ragnar is finally available for NixOS, the package has been merge to nixpkgs unstable :eyes:

**Pull request merged**
